In [1]:
import numpy as np

In [4]:
pip install pandas

In [2]:
#Exercise 1
a1=np.arange(1,11).reshape(2,5)
print(a1)
print(a1.shape)
print(a1.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2


In [3]:
#Exercise 2
a2=np.arange(1,21)
print(a2)
print(a2[5:15])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15]


In [4]:
#Exercise 3
import pandas as pd

In [6]:
fruit=pd.Series({'apple':3,'bananas':2,'oranges':1})
print(fruit)
fruit['pears']=4
print(fruit)

apple      3
bananas    2
oranges    1
dtype: int64
apple      3
bananas    2
oranges    1
pears      4
dtype: int64


In [7]:
#Exercise 4
df=pd.DataFrame({
    'name':['Frank', 'Alice', 'Bob', 'Grazy', 'Ann', 
            'Charly', 'David', 'Jian', 'Harry', 'Rose'],
    'age':[20,23,24,22,20,34,43,36,37,33],
    'gender':['Male', 'Female', 'Male', 'Female', 'Female', 
              'Male', 'Male', 'Male', 'Male', 'Female']
})

df

name  age  gender
0   Frank   20    Male
1   Alice   23  Female
2     Bob   24    Male
3   Grazy   22  Female
4     Ann   20  Female
5  Charly   34    Male
6   David   43    Male
7    Jian   36    Male
8   Harry   37    Male
9    Rose   33  Female

In [10]:
#Exercise 5

df['occupation']=['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer', 'Analyst', 'Manager', 'Programmer', 'Analyst', 'Analyst']
df

name  age  gender  occupation
0   Frank   20    Male  Programmer
1   Alice   23  Female     Manager
2     Bob   24    Male     Analyst
3   Grazy   22  Female     Manager
4     Ann   20  Female  Programmer
5  Charly   34    Male     Analyst
6   David   43    Male     Manager
7    Jian   36    Male  Programmer
8   Harry   37    Male     Analyst
9    Rose   33  Female     Analyst

In [11]:
#Exercise 6

age_condition=df[df['age']>=30]
print(age_condition)

     name  age  gender  occupation
5  Charly   34    Male     Analyst
6   David   43    Male     Manager
7    Jian   36    Male  Programmer
8   Harry   37    Male     Analyst
9    Rose   33  Female     Analyst


In [13]:
#Exercise 7

df.to_csv('Employee.csv', index=False)
print("df saved as 'Employee.csv'.")
df_csv_read=pd.read_csv('Employee.csv')
print(df_csv_read)

df saved as 'Employee.csv'.
     name  age  gender  occupation
0   Frank   20    Male  Programmer
1   Alice   23  Female     Manager
2     Bob   24    Male     Analyst
3   Grazy   22  Female     Manager
4     Ann   20  Female  Programmer
5  Charly   34    Male     Analyst
6   David   43    Male     Manager
7    Jian   36    Male  Programmer
8   Harry   37    Male     Analyst
9    Rose   33  Female     Analyst
